// Build-time proto embedding script.
// Reads proto/cambrian.proto and proto/operator.proto and generates
// src/proto-embed.ts with both as embedded string constants.
//
// CAMBRIAN_PROTO  — agent-plane (Orchestrator / AgentService). Used by
//                   tool/skill/memory/watches/exec RPCs (CLI-001 "what
//                   stays on Orchestrator").
// OPERATOR_PROTO  — operator-plane (OperatorConsole, ADR-0047). Used by
//                   login, snapshot, StreamEvents, ResolveHITL, QueryAudit,
//                   and other command RPCs.
//
// Both are vendored copies of the kernel's source of truth
// (api/proto/{cambrian,operator}.proto). When the contract bumps,
// re-vendor and re-run this script.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const ROOT = resolve(__dirname, "..");

function escape(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

function main() {
  const agentPath = resolve(ROOT, "proto/cambrian.proto");
  const operatorPath = resolve(ROOT, "proto/operator.proto");
  const outputPath = resolve(ROOT, "src/proto-embed.ts");

  const cambrian = escape(readFileSync(agentPath, "utf-8"));
  const operator = escape(readFileSync(operatorPath, "utf-8"));

  const output = `// AUTO-GENERATED by scripts/embed-proto.ts — DO NOT EDIT
// Contains both protos as embedded strings.
// Used by grpc/client.ts (agent-plane) and grpc/operator-client.ts (operator-plane)
// to avoid runtime filesystem dependency.

export const CAMBRIAN_PROTO = \`${cambrian}\`;

export const OPERATOR_PROTO = \`${operator}\`;
`;

  writeFileSync(outputPath, output, "utf-8");
  console.log(`✓ Embedded protos → ${outputPath}`);
}

main();
